#ifndef __SWCHANNELLOGO_H__
#define __SWCHANNELLOGO_H__

typedef enum
{
	PARA_NUM_ERROR = 101000,
	VERSION_NUM_ERROR,
	NO_LOGO_FILE,
	LOGO_FILE_OUT_MEM,
	MAKE_SUCCESS,
	NO_ALL_IS_DIG,
	LIB_TOOL_ERROR,
	PRIVATE_KEY_ERROR,
	SYSTEM_ERROR,
}erro_type_t;

#endif
